################################### English language #####################################
[en]
languageName = "en"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home - Motocam.NZ"
# footer content
footer_content = "Photo, video and broadcast with custom equipped motorcycles."
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

################################### French language #####################################
