baseURL: https://wearetechnative.github.io/quiqr-template-bexer-remix/
title: Motocam.NZ
theme:
  - bexer-hugo
  - hugo-debugprint
paginate: '6'
summaryLength: '10'
googleAnalytics: ''
disableLanguages: []
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
markup:
  goldmark:
    renderer:
      unsafe: true
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
  text/netlify:
    delimiter: ''
    suffixes:
      - ''
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
languages:
  en:
    menu:
      main: null
    languageName: En
    languageCode: en-us
    contentDir: content/english
    weight: 1
    home: home
    copyright: All Rights Reserved © 2025
    footer_content: '**Photo, video and broadcast with custom equipped motorcycles.**'
params:
  debugprint: true
  logo: Motocam.nz.png
  logo_width: 150px
  logo_footer: Motocam.nz.png
  favicon: Motocam.nz.png
  top_header: false
  description: Photo, video and broadcast with custom equipped motorcycles.
  author: Themefisher
  contact_form_action: '#'
  google_analitycs_id: ''
  address: Auckland, New Zealand
  mobile: ''
  email: contact@motocam.nz
  quick_contact: false
  search: false
  mainSections:
    - blog
    - service
    - project
  preloader:
    enable: false
    preloader: ''
  navigation_button:
    enable: false
    label: download now
    link: https://github.com/wearetechnative/quiqr-template-bexer-remix
  subscription:
    enable: false
    mailchimp_form_action: >-
      https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
  gmap:
    enable: true
    gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
    map_marker_name: marker.png
    resources: []
  social:
    - icon: fab fa-facebook
      link: https://www.facebook.com/Motocam.NZ
  resources: []
  menus_alt:
    main:
      - name: Why Bexer Remix
        url: ''
        submenus:
          - name: Local First
            url: ./
            disabled: false
          - name: Made for Hugo
            url: https://gohugo.io
            disabled: false
          - name: Secure by design
            url: ./
            disabled: false
          - name: Free forever
            url: https://github.com/wearetechnative/quiqr-template-bexer-remix
            disabled: false
          - name: Blazingly Fast
            url: ./
            disabled: false
        disabled: true
      - name: Download Quiqr
        url: pages/download
        disabled: true
        submenus: []
      - name: Projects
        submenus: []
        url: project
        disabled: true
      - name: Blog
        url: blog
        disabled: true
        submenus: []
      - name: about
        url: /pages/about
        disabled: true
        submenus: []
      - name: We hiring
        url: career
        disabled: true
        submenus: []
    footer: []
  top_menu_vertical_margin: '8'
