baseURL: https://wearetechnative.github.io/quiqr-template-bexer-remix/
title: Motocam.NZ
theme:
  - bexer-hugo
  - hugo-debugprint
paginate: '6'
summaryLength: '10'
googleAnalytics: ''
disableLanguages: []
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
markup:
  goldmark:
    renderer:
      unsafe: true
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
  text/netlify:
    delimiter: ''
    suffixes:
      - ''
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
params:
  debugprint: true
  logo: Motocam.nz.png
  logo_width: 150px
  logo_footer: Motocam.nz.png
  favicon: Motocam.nz.png
  top_header: false
  description: Photo, video and broadcast with custom equipped motorcycles.
  author: Themefisher
  contact_form_action: '#'
  google_analitycs_id: ''
  address: Auckland, New Zealand
  mobile: ''
  email: contact@motocam.nz
  quick_contact: false
  search: false
  mainSections:
    - blog
    - service
    - project
  preloader:
    enable: false
    preloader: ''
  navigation_button:
    enable: false
    label: download now
    link: https://github.com/wearetechnative/quiqr-template-bexer-remix
  subscription:
    enable: false
    mailchimp_form_action: >-
      https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
  gmap:
    enable: false
    gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
    map_marker_name: marker.png
    resources: []
  social:
    - icon: fab fa-facebook
      link: https://www.facebook.com/Motocam.NZ
  resources: []
  top_menu_vertical_margin: '8'
